[package]
name = "adventofcode21"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day1"
path = "src/day_1.rs"

[[bin]]
name = "day2"
path = "src/day_2.rs"

[[bin]]
name = "day3"
path = "src/day_3.rs"

[dependencies]
itertools = "0.10"
